Category.destroy_all
Size.destroy_all
Item.destroy_all
Cost.destroy_all

small = Size.create(name: 'Small')
large = Size.create(name: 'Large')
order = Size.create(name: 'Order')
pint = Size.create(name: 'Pint')
quart = Size.create(name: 'Quart')

appetizers = Category.create(name: 'Appetizers', ordinal: 1)
soups = Category.create(name: 'Soup', ordinal: 2, description: 'w. Crispy Noodles')
fried_rice = Category.create(name: 'Fried Rice', ordinal: 3)
chow_mein = Category.create(name: 'Chow Mein or Chop Suey', ordinal: 4, description: 'served w. Crispy Noodles & White Rice')
chow_fun = Category.create(name: 'Chow Fun or Chow Mai Fun', ordinal: 5, description: 'Soft Rice Noodle')
lo_mein = Category.create(name: 'Lo Mein', ordinal: 6, description: 'Soft Noodle')
side_orders = Category.create(name: 'Side Orders', ordinal: 7)
egg_foo_young = Category.create(name: 'Egg Foo Young', ordinal: 8, description: 'w. White Rice')
sweet_sour = Category.create(name: 'Sweet & Sour', ordinal: 9, description: 'w. White Rice')
beef = Category.create(name: 'Beef', ordinal: 10, description: 'w. White Rice')
pork = Category.create(name: 'Pork', ordinal: 11, description: 'w. White Rice')
chicken = Category.create(name: 'Chicken', ordinal: 12, description: 'w. White Rice')
seafood = Category.create(name: 'Seafood', ordinal: 13, description: 'w. White Rice')
moo_shu = Category.create(name: 'Moo Shu', ordinal: 14, description: 'w. 5 Pancakes & Rice')
vegetables = Category.create(name: 'Vegetables', ordinal: 15, description: 'w. White Rice')
health_food_selection = Category.create(name: 'Health Food Selection', ordinal: 16, description: 'Low Calories, Steamed w. White Rice, Sauce on Side')
combination_platters = Category.create(name: 'Combination Platters', ordinal: 17, description: 'Served w. an Egg Rol & Fried Rice')
house_specialties = Category.create(name: 'House Specialties', ordinal: 18, description: 'w. White Rice')
lunch_special = Category.create(name: 'Lunch Special', ordinal: 19)
specialties = Category.create(name: 'Our Specialties', ordinal: 20)

def item(group, ordinal, name, amount, size, sub_ordinal = 0)
  item = group.items.create(name: name, ordinal: ordinal, sub_ordinal: sub_ordinal)
  cost(item, amount, size)
  item
end

def itemh(group, ordinal, name, amount, size, sub_ordinal = 0)
  item = item(group, ordinal, name, amount, size, sub_ordinal)
  hot(item)
  item
end

def itempq(group, ordinal, name, pint, quart, sub_ordinal = 0)
  item = group.items.create(name: name, ordinal: ordinal, sub_ordinal: sub_ordinal)
  cost(item, pint, Size.find_by_name('Pint'))
  cost(item, quart, Size.find_by_name('Quart'))
  item
end

def itemq(group, ordinal, name, quart, sub_ordinal = 0)
  item = group.items.create(name: name, ordinal: ordinal, sub_ordinal: sub_ordinal)
  cost(item, quart, Size.find_by_name('Quart'))
  item
end

def itemo(group, ordinal, name, amount, sub_ordinal = 0)
  item = group.items.create(name: name, ordinal: ordinal, sub_ordinal: sub_ordinal)
  cost(item, amount, Size.find_by_name('Order'))
  item
end

def itemoh(group, ordinal, name, amount, sub_ordinal = 0)
  item = group.items.create(name: name, ordinal: ordinal, sub_ordinal: sub_ordinal)
  cost(item, amount, Size.find_by_name('Order'))
  hot(item)
  item
end

def hot(item)
  item.hot = true
  item.save
end

def description(item, description)
  item.description = description
  item.save
end

def cost(item, amount, size)
  item.costs.create(amount: amount, size: size)
end

item(appetizers, 1, 'Egg Roll', 1.3, order)
item(appetizers, 2, 'Shrimp Roll', 1.35, order)
item(appetizers, 3, 'Spring Roll', 2.95, order)
item(appetizers, 4, 'Dumplings', 5.8, order)
item(appetizers, 5, 'Cold Sesame Noodles', 4.4, order)
item(appetizers, 6, 'Shrimp Toast', 3.95, order)
item(appetizers, 7, 'Chicken Wings', 5.4, order)
item(appetizers, 7, 'Half Chicken', 4.95, order, 1)
item(appetizers, 8, 'Fantail Shrimps', 5.05, order)
item(appetizers, 9, 'Steak on Sticks', 6.4, order)
item(appetizers, 9, 'Chicken on Sticks', 6.4, order, 1)
item(appetizers, 10, 'Roast Pork Slices or Ends', 7.10, order)
item(appetizers, 11, 'Fried or Steamed Wontons', 4.19, order)
item = item(appetizers, 12, 'Bar-B-Q Spare Ribs', 6.99, small)
cost(item, 12.10, large)
item(appetizers, 13, 'Pu Pu Platter', 11.15, order)
item = item(appetizers, 14, 'Boneless Ribs', 6.99, small)
cost(item, 12.10, large)
item = item(appetizers, 15, 'Pan Fried Wontons', 4.6, order)
hot(item)
description(item, 'w. Szechuan Sauce')
item(appetizers, 15, 'Scallion Pancake', 3.49, order, 1)
item = item(appetizers, 15, 'Chicken Dumplings', 5.8, order, 2)
description(item, 'Fried or Steamed')
item(appetizers, 16, 'Crab Rangoon', 4.9, order)
item(appetizers, 16, 'Dim Sum', 4.85, order, 1)
item = item(appetizers, 16, 'Vegetable Dumplings', 5.5, order, 2)
description(item, 'Fried or Steamed')
item(appetizers, 16, 'Shrimp Dumplings', 4.99, order, 3)
item(appetizers, 16, 'Pork Bun', 3.55, order, 4)
item(appetizers, 16, 'Thai Sweet Chili Wings', 5.9, order, 5)

item = item(soups, 17, 'Roast Pork Wonton Soup', 1.95, pint)
cost(item, 3.4, quart)
item = item(soups, 18, 'Egg Drop Soup', 1.9, pint)
cost(item, 3, quart)
item = item(soups, 19, 'Wonton w. Egg Drop', 2.25, pint)
cost(item, 3.9, quart)
item = item(soups, 20, 'Chicken Rice or Noodle', 2.2, pint)
cost(item, 3.5, quart)
item = item(soups, 21, 'Chinese Vegetable Soup', 2.05, pint)
cost(item, 3.5, quart)
item = item(soups, 22, 'Hot & Sour Soup', 2.45, pint)
cost(item, 4.35, quart)
hot(item)
item(soups, 23, 'House Special Soup w. Wonton', 6, quart)
item(soups, 24, 'Roast Pork or Chicken Yat Gaw Mein', 5, quart)
item(soups, 25, 'House Speical Yat Gaw Mein', 6, quart)
item(soups, 26, 'Seafood Soup', 7, quart)

itempq(fried_rice, 27, 'Roast Pork Fried Rice', 3.85, 6.95)
itempq(fried_rice, 28, 'Chicken Fried Rice', 3.85, 6.95)
itempq(fried_rice, 29, 'Shrimp Fried Rice', 4.5, 7.8)
itempq(fried_rice, 30, 'Beef Fried Rice', 4.5, 7.8)
itempq(fried_rice, 31, 'Vegetable Fried Rice', 3.5, 6.2)
itempq(fried_rice, 32, 'House Special Fried Rice', 4.5, 7.85)
itempq(fried_rice, 33, 'Young Chow Fried Rice', 4.5, 7.85)

itempq(chow_mein, 34, 'Chicken Chow Mein', 4.8, 7.6)
itempq(chow_mein, 35, 'Shrimp Chow Mein', 5.05, 7.15)
itempq(chow_mein, 36, 'Beef Chow Mein', 5.05, 7.95)
itempq(chow_mein, 37, 'Roast Pork Chow Mein', 4.8, 7.4)
itempq(chow_mein, 38, 'Vegetable Chow Mein', 4.55, 6.65)
itempq(chow_mein, 39, 'House Special Chow Mein', 5.25, 8.45)

item(chow_fun, 40, 'Roast Pork Chow Fun or Chai Mai Fun', 7.95, order)
item(chow_fun, 41, 'Chicken Chow Fun or Chai Mai Fun', 8.15, order)
item(chow_fun, 42, 'Shrimp Chow Fun or Chai Mai Fun', 8.4, order)
item(chow_fun, 43, 'Beef Chow Fun or Chai Mai Fun', 8.4, order)
item(chow_fun, 44, 'Vegetable Chow Fun or Chai Mai Fun', 7.65, order)
item(chow_fun, 45, 'House Special Chow Fun or Chai Mai Fun', 8.85, order)
itemh(chow_fun, 46, 'Singapore Chow Mei Fun', 8.85, order)
itemh(chow_fun, 46, 'Pad Thai Chicken or Shrimp', 8.95, order, 1)

itempq(lo_mein, 47, 'Roast Pork Lo Mein', 4.6, 7.35)
itempq(lo_mein, 48, 'Chicken Lo Mein', 4.6, 7.6)
itempq(lo_mein, 49, 'Shrimp Lo Mein', 4.95, 8.15)
itempq(lo_mein, 50, 'Beef Lo Mein', 4.95, 8.15)
itempq(lo_mein, 51, 'Vegetable Lo Mein', 4.15, 6.25)
itempq(lo_mein, 52, 'House Special Lo Mein', 5.35, 8.55)

item(side_orders, 1, 'Fortune Cookies', 1.35, order)
item(side_orders, 2, 'Almond Cookies', 1.45, order)
itempq(side_orders, 3, 'White Rice', 1.5, 2.6)
item(side_orders, 4, 'Crispy Noodle', 0.65, order)
itempq(side_orders, 5, 'Brown Rice', 1.9, 3.4)

itemq(egg_foo_young, 53, 'Roast Pork Egg Foo Young', 7.25)
itemq(egg_foo_young, 54, 'Chicken Egg Foo Young', 7.25)
itemq(egg_foo_young, 55, 'Shrimp Egg Foo Young', 7.85)
itemq(egg_foo_young, 56, 'Vegetable Egg Foo Young', 7)
itemq(egg_foo_young, 57, 'Beef Egg Foo Young', 7.85)
itemq(egg_foo_young, 57, 'Mushroom Egg Foo Young', 7.1, 1)

itempq(sweet_sour, 58, 'Sweet & Sour Pork', 4.7, 7.99)
itempq(sweet_sour, 59, 'Sweet & Sour Chicken', 4.7, 7.99)
itempq(sweet_sour, 60, 'Sweet & Sour Shrimp', 5.25, 8.75)
itemq(sweet_sour, 61, 'Sweet & Sour Combo', 9.35)

itempq(beef, 62, 'Beef w. Bean Sprouts', 5.9, 9.8)
itempq(beef, 63, 'Pepper Steak w. Onion', 5.9, 9.8)
itempq(beef, 64, 'Pepper Steak w. Tomato', 5.9, 9.8)
itempq(beef, 65, 'Beef w. Mushrooms', 5.9, 9.8)
itempq(beef, 66, 'Beef w. Chinese Vegetable', 5.9, 9.8)
itempq(beef, 67, 'Beef w. Oyster Sauce', 5.9, 9.8)
itempq(beef, 68, 'Beef w. Black Bean Sauce', 5.9, 9.8)
item = itempq(beef, 69, 'Curry Beef', 5.9, 9.8)
hot(item)
itempq(beef, 70, 'Beef w. Broccoli', 5.9, 9.8)
itempq(beef, 70, 'Beef w.  Mixed Vegetables', 5.9, 9.8)
itempq(beef, 71, 'Beef w. Snow Pea Pods', 5.9, 9.8)
itempq(beef, 72, 'Beef w. String Beans', 5.9, 9.8)
item = itempq(beef, 73, 'Beef w. Eggplant in Garlic Sauce', 5.9, 9.8)
hot(item)
itemh(beef, 74, 'Hunan Beef', 9.8, quart)
itemh(beef, 75, 'Beef w. Szechuan Sauce', 9.8, quart)
itemh(beef, 76, 'Hot & Spicy Shredded Beef', 9.8, quart)
itemh(beef, 77, 'Beef w. Garlic Sauce', 9.8, quart)

itempq(pork, 78, 'Roast Prok w. Mixed Vegetables', 5.35, 9.1)
itempq(pork, 79, 'Roast Prok w. Mushrooms', 5.35, 9.1)
itempq(pork, 80, 'Roast Prok w. Black Bean Sauce', 5.35, 9.1)
itempq(pork, 81, 'Roast Prok w. Oyster Sauce', 5.35, 9.1)
itempq(pork, 82, 'Roast Prok w. Ban Sprouts', 5.35, 9.1)
itempq(pork, 83, 'Roast Prok w. Snow Pea Pods', 5.35, 9.1)
itempq(pork, 84, 'Roast Prok w. Broccoli', 5.35, 9.1)
itempq(pork, 85, 'Roast Prok w. StringBeans', 5.35, 9.1)
item = itempq(pork, 86, 'Roast Prok w. Eggplant in Garlic Sauce', 5.35, 9.1)
hot(item)
itemh(pork, 87, 'Hunan Pork', 9.1, quart)
itemh(pork, 88, 'Pork w. Szechuan Sauce', 9.1, quart)
itemh(pork, 89, 'Pork w. Garlic Sauce', 9.1, quart)
itemh(pork, 90, 'Hot & Spicy Shredded Pork', 9.1, quart)

itempq(chicken, 91, 'Chicken w. Mixed Vegetables', 5.7, 9.25)
itempq(chicken, 92, 'Chicken Almond', 5.7, 9.25)
itempq(chicken, 93, 'Chicken w. Black Bean Sauce', 5.7, 9.25)
item = itempq(chicken, 94, 'Curry Chicken', 5.7, 9.25)
hot(item)
itempq(chicken, 95, 'Chicken w. Bean Sprouts', 5.7, 9.25)
itempq(chicken, 96, 'Chicken w. Broccoli', 5.7, 9.25)
itempq(chicken, 97, 'Chicken w. Cashew Nuts', 5.7, 9.25)
itempq(chicken, 98, 'Chicken w. String Beans', 5.7, 9.25)
item = itempq(chicken, 99, 'Chicken w. Eggplant in Garlic Sauce', 5.7, 9.25)
hot(item)
itempq(chicken, 100, 'Chicken w. Snow Peas', 5.7, 9.25)
itempq(chicken, 101, 'Moo Goo Gai Pan', 5.7, 9.25)
itemh(chicken, 102, 'Hunan Chicken', 9.25, quart)
itemh(chicken, 103, 'Chicken w. Szechuan Sauce', 9.25, quart)
itemh(chicken, 104, 'Kung Bo Chicken', 9.25, quart)
itemh(chicken, 105, 'Chicken w. Garlic Sauce', 9.25, quart)
itemh(chicken, 106, 'Hot & Spicy Shredded Chicken', 9.25, quart)

itempq(seafood, 107, 'Shrimp w. Lobster Sauce', 6.15, 10.25)
itempq(seafood, 108, 'Shrimp w. Mushrooms', 6.15, 10.25)
itempq(seafood, 109, 'Shrimp w. Mixed Vegetables', 6.15, 10.25)
itempq(seafood, 110, 'Shrimp w. Bean Sprouts', 6.15, 10.25)
itempq(seafood, 111, 'Shrimp w. Black Bean Sauce', 6.15, 10.25)
item = itempq(seafood, 112, 'Curry Shrimp', 6.15, 10.25)
hot(item)
itempq(seafood, 113, 'Shrimp w. Broccoli', 6.15, 10.25)
itempq(seafood, 114, 'Shrimp w. Eggplant in Garlic Sauce', 6.15, 10.25)
itempq(seafood, 115, 'Shrimp w. Snow Pea Pods', 6.15, 10.25)
itempq(seafood, 116, 'Shrimp w. Almond Ding', 6.15, 10.25)
itempq(seafood, 117, 'Shrimp w. Chinese Vegetable', 6.15, 10.25)
itemh(seafood, 119, 'Hunan Shrimp', 10.25, quart)
itemh(seafood, 120, 'Shrimp w. Garlic Sauce', 10.25, quart)
itemh(seafood, 121, 'Shrimp w. Szechuan Sauce', 10.25, quart)
itemh(seafood, 122, 'Shrimp & Scallops w. Garlic Sauce', 10.25, quart)
itemq(seafood, 123, 'Butterfly Shrimp', 10.25)
itemq(seafood, 123, 'Shrimp w. String Beans', 10.25, 1)
itemq(seafood, 123, 'Shrimp w. Cashew Nuts', 10.25, 2)

itemo(moo_shu, 124, 'Moo Shu Pork or Chicken', 8.4)
itemo(moo_shu, 125, 'Moo Shu Shrimp or Beef', 8.85)
itemo(moo_shu, 126, 'Moo Shu Vegetable', 7.9)

itemo(vegetables, 127, 'Sauteed Broccoli', 7.25)
itemo(vegetables, 128, 'Mixed Chinese Vegetables', 7.25)
itemo(vegetables, 129, 'Sauteed Snow Peas', 7.25)
itemo(vegetables, 130, 'Buddhist Delight', 7.25)
itemo(vegetables, 131, 'Sauteed String Beans', 7.25)
item = itemo(vegetables, 132, 'Broccoli w. Garlic Sauce', 7.25)
hot(item)
item = itemo(vegetables, 133, 'Mixed Vegetables w. Garlic Sauce', 7.25)
hot(item)
item = itemo(vegetables, 133, 'Szechuan Bean Cake', 7.25, 1)
hot(item)
itemo(vegetables, 133, 'Bean Cake w. Oyster Sauce', 7.25, 2)
item = itemo(vegetables, 134, 'String Bean w. Garlic Sauce', 7.25)
hot(item)
item = itemo(vegetables, 135, 'Chinese Eggplant w. Garlic Sauce', 7.25)
hot(item)

itemo(health_food_selection, 136, 'Steamed Mixed Vegetables w. Shrimp', 10.25)
itemo(health_food_selection, 137, 'Steamed Mixed Vegetables w. Chicken', 9.25)
itemo(health_food_selection, 138, 'Steamed Beef w. Broccoli', 9.8)
itemo(health_food_selection, 139, 'Steamed Chicken w. Broccoli', 9.25)
itemo(health_food_selection, 140, 'Steamed Mixed Vegetables', 7.25)
itemo(health_food_selection, 141, 'Steamed String Beans', 7.25)
itemo(health_food_selection, 142, 'Steamed Broccoli', 7.25)
itemo(health_food_selection, 143, 'Steamed Chicken w. String Beans', 9.25)

itemo(combination_platters, 1, 'Chicken or Roast Pork Chown Mein', 7.7)
itemo(combination_platters, 2, 'Shrimp or Beef Chow Mein', 7.9)
itemo(combination_platters, 3, 'Pork or Chicken Lo Mein', 7.7)
itemo(combination_platters, 4, 'Shrimp or Beef Lo Mein', 7.9)
itemo(combination_platters, 5, 'Chicken or Roast Pork Egg Foo Young', 7.6)
itemo(combination_platters, 6, 'Pepper Steak w. Onoin', 8.05)
itemo(combination_platters, 7, 'Roast Pork w. Mixed Vegetables', 7.8)
itemo(combination_platters, 8, 'Sweet & Sour Pork or Chicken', 7.6)
itemo(combination_platters, 9, 'Bar-B-Q Spare Ribs or Boneless Ribs', 8.6)
itemo(combination_platters, 10, 'Shrimp w. Lobster Sauce', 8.4)
itemo(combination_platters, 11, 'Beef w. Mushrooms', 8.4)
itemo(combination_platters, 12, 'Beef or Chicken w. Broccoli', 8.15)
item = itemo(combination_platters, 13, 'Gong Bo Gai Ding (Chicken)', 8.15)
hot(item)
item = itemo(combination_platters, 14, 'Shrimp, Beef or Chicken w. Garlic Sauce', 8.4)
hot(item)
itemo(combination_platters, 15, 'Sesame Chicken', 8.5)
item = itemo(combination_platters, 16, 'General Tso\'s Chicken', 8.5)
hot(item)
itemo(combination_platters, 17, 'Shrimp or Beef w. Mixed Vegetables', 8.4)
itemo(combination_platters, 18, 'Chicken w. Mixed Vegetable', 8.15)
itemo(combination_platters, 19, 'Moo Goo Gai Pan', 8.15)
itemo(combination_platters, 20, 'Chicken w. String Beans', 8.15)
itemo(combination_platters, 21, 'Mixed Vegetables', 7.4)
itemo(combination_platters, 22, 'Shrimp w. Broccoli', 8.4)

itemo(house_specialties, 1, 'Sesame Chicken', 9.29)
item = itemo(house_specialties, 2, 'General Tso\'s Chicken', 9.29)
hot(item)
itemo(house_specialties, 2, 'General Tso\'s To Fu', 8.29, 1)
hot(item)
itemo(house_specialties, 2, 'Sesame To Fu', 8.29, 2)
item = itemo(house_specialties, 3, 'Four Seasons', 10.45)
description(item, 'Beef, roast prok, chicken, jumbo shrimp & mixed Chinese vegetables in brown sauce')
item = itemo(house_specialties, 4, 'Happy Family', 11.5)
description(item, 'Lobster meat, pork, chicken, shrimp, beef & mixed Chinese vegetables in brown sauce')
item = itemo(house_specialties, 5, 'Seafood Combination', 11.95)
description(item, 'Fresh jumbo shrimps, scallops, crab meat all sauteed w. lobster meat, mushroom, baby corn, carrots, Chinese vegetable, snow peas in white wine sauce')
item = itemo(house_specialties, 6, 'House Special Pan Fried Noodles', 11.3)
description(item, 'Jumbo shrimp, chicken, beef & pork w. mixed vegetables over pan fried noodles')
item = itemo(house_specialties, 7, 'Crispy Orange Flavor Beef or Chicken', 10.4)
hot(item)
item = itemo(house_specialties, 8, 'Lover\'s Nest', 11.95)
description(item, 'Lobster meat, jumbo shrimp, sea scallops, crab meat, sauteed w. vegetables in a delicious white sauce. Served in a nest made w. Chinese taro')
item = itemo(house_specialties, 9, 'Hot & Spicy Scallops', 10.95)
hot(item)
itemo(house_specialties, 10, 'Triple Delights', 10.45)
description(item, 'Jumbo shrimp, chicken, roast pork w. broccoli, Chinese vegetables, snow peas, baby corn, water-chestnuts & straw mushrooms')
item = itemo(house_specialties, 11, 'Seafood w. Garlic Sauce', 11.95)
description(item, 'Lobster meat, shrimp, scallops, crab stick w. mixed vegetables in fresh garlic sauce')
hot(item)
item = itemo(house_specialties, 12, 'Roast Duck', 13.4)
description(item, 'Roast Peking Duck served w. pancakes along w. scallion brushes & hoisin sauce')
item = itemo(house_specialties, 13, 'Hunan Chicken & Shrimp', 10.75)
description(item, 'Sliced chicken & shrimp w. vegetable delightful in spicy sauce')
hot(item)
item = itemo(house_specialties, 14, 'Hunan Beef & Shrimp', 10.75)
hot(item)
item = itemo(house_specialties, 15, 'Dragon & Phoenix', 11.25)
description(item, 'Two dishes in one jumbo shrimp sauteed in a spicy garlic sauce balanced w. General Tso\'s chicken on the other side')
hot(item)
itemo(house_specialties, 16, 'Boneless Chicken w. Vegetable', 9.45)
itemo(house_specialties, 17, 'Lemon Chicken', 9.45)
item = itemo(house_specialties, 18, 'Subgum Wonton', 10.85)
description(item, 'King crab meat, sliced chicken, roast pork, shrimp, imported straw mushrooms, bamboo shoots, water-chestnuts & Chinese vegetable, baby corn served w. crispy wonton')
item = itemo(house_specialties, 19, 'Szechuan Seafood Plates', 11.95)
description(item, 'Lobster meat, jumbo shrimp, scallops, crab stick w. mixed vegetables in Szechuan hot peeper sauce')
hot(item)
item = itemo(house_specialties, 20, 'Hunan Combination', 11.4)
description(item, 'Sliced beef, scallops & shrimps w. broccoli, bamboo shoots & waterchestnuts')
hot(item)
itemo(house_specialties, 21, 'Honey Shrimp', 10.3)
item = itemo(house_specialties, 22, 'Sa-Cha Beef or Chicken', 9.3)
description(item, 'Beef or chicken w. red & green pepper, baby corn, snow peas, mushrooms sa-cha & kung bo sauce')
item = itemo(house_specialties, 23, 'Beef w. Scallions', 10.25)
hot(item)
item = itemo(house_specialties, 24, 'Double Delight (Shrimp & Chicken)', 10.3)
hot(item)
item = itemo(house_specialties, 25, 'Hot & Spicy Shrimp', 10.35)
hot(item)
item = itemo(house_specialties, 26, 'White Meat General Tao\'s Chicken or Sesame Chicken', 9.8)
hot(item)

itemo(lunch_special, 1, 'Chow Mein (Chicken or Pork)', 6.19)
itemo(lunch_special, 2, 'Shrimp Chow Mein', 6.19)
itemo(lunch_special, 3, 'Lo Mein (Chicken or Pork)', 6.19)
itemo(lunch_special, 4, 'Shrimp or Beef Lo Mein', 6.19)
itemo(lunch_special, 5, 'Egg Foo Young (Chicken or Pork)', 6.19)
itemo(lunch_special, 6, 'Shrimp or Beef Egg Foo Young', 6.19)
itemo(lunch_special, 7, 'Pepper Steak or Chicken', 6.29)
itemo(lunch_special, 8, 'Pork or Chicken or Beef w. Broccoli', 6.29)
itemo(lunch_special, 9, 'Shrimp w. Broccoli or String Beans', 6.29)
itemo(lunch_special, 10, 'Sweet & Sour Chicken or Pork', 6.19)
itemo(lunch_special, 11, 'Pork or Chicken or Beef or Shrimp w. Mixed Vegetables', 6.29)
itemo(lunch_special, 12, 'Pork or Chicken or Beef w. String Beans', 6.29)
itemo(lunch_special, 13, 'Pork or Chicken or Beef or Shrimp w. Black Bean Sauce', 6.29)
itemo(lunch_special, 14, 'Chicken or Shrimp w. Cashew Nuts', 6.29)
itemoh(lunch_special, 15, 'Broccoli w. Garlic Sauce', 5.9)
itemoh(lunch_special, 16, 'Hot & Spicy Pork or Chicken or Beef or Shrimp', 6.29)
itemoh(lunch_special, 17, 'Pork or Chicken or Beef or Shrimp w. Garlic Sauce', 6.29)
itemoh(lunch_special, 18, 'General Tso\'s Chicken', 6.5)
itemo(lunch_special, 19, 'Sesame Chicken', 6.5)
itemo(lunch_special, 20, 'Chicken Wings', 6.85)
itemo(lunch_special, 21, 'Roast Prok Ends or Slices', 6.59)
itemo(lunch_special, 22, 'B-B-Q Ribs or Boneless Ribs', 6.59)
itemo(lunch_special, 23, 'Sauteed Mixed Vegetable', 5.9)
itemo(lunch_special, 24, 'Shrimp w. Lobster Sauce', 6.25)
itemo(lunch_special, 25, 'Bean Sprouts (Chicken or Pork or Beef)', 6.19)
itemo(lunch_special, 26, 'Shrimp w. Bean Sprouts', 6.19)
itemo(lunch_special, 27, 'Pork, Chicken, Beef or Shrimp Sauteed w. Bean Cakes', 6.19)
itemoh(lunch_special, 28, 'Hunan Beef or Chicken or Shrimp', 6.29)
itemoh(lunch_special, 29, 'Chicken or Shrimp or Beef in Szechuan Sauce', 6.29)
itemoh(lunch_special, 30, 'Chicken w. Eggplant w. Garlic Sauce', 6.29)
itemo(lunch_special, 31, 'Moo Goo Gai Pan', 6.29)

itemo(specialties, 1, 'Plain Chicken Wings', 4.4)
itemo(specialties, 2, 'Plain Chicken Wings with Plain Fried Rice and French Fries', 5.9)
itemo(specialties, 3, 'Plain Chicken Wings with Pork or Chicken Fried Rice', 5.95)
itemo(specialties, 4, 'Plain Chicken Wings with Beef or Shrimp Fried Rice', 6.95)
itemo(specialties, 5, 'Plain Half Chicken', 4.95)
itemo(specialties, 6, 'Plain Half Chicken with Plain Fried Rice and French Fries', 6.3)
itemo(specialties, 7, 'Plain Half Chicken with Pork or Chicken Fried Rice', 6.55)
itemo(specialties, 8, 'Plain Half Chicken with Beef or Shrimp Fried Rice', 7.6)
itemo(specialties, 9, 'French Fries', 3.55)
